### ISSUE TITLE
"ensure" function could be a good fit for this package

### ISSUE THREAD

**Issue by moltar** [jedmao/lavadrop#44]
# Feature Request

This is one thing I found myself copy pasting recently.

```ts
/**
 * Ensures that a value is returned from .find method. This removes the possibility of value being undefined.
 *
 * @example
 *
 * // item will never be undefined
 * const item = ensure(items.find(item => item.id === 1))
 *
*/
export function ensure<T>(argument: T | undefined | null, message: string = 'Did not find.'): T {
  if (argument === undefined || argument === null) {
    throw new TypeError(message)
  }

  return argument
}
```

**Comment by jedmao** [comment]
Thanks for submitting the issue!

Your timing is perfect, because I just read the [TypeScript 3.7 RC announcement](https://devblogs.microsoft.com/typescript/announcing-typescript-3-7-rc/), where it shows assertion functions. With that, I believe the following code would meet all of your requirements, correct?

```ts
function ensure<T>(val: T): asserts val is NonNullable<T> {
    if (val === undefined || val === null) {
        throw new AssertionError(
            `Expected 'val' to be defined, but received ${val}`
        )
    }

    return val
}
```

I would be super happy to introduce this function. It seems like a perfect addition to this library.

Thanks so much!

**Comment by jedmao** [comment]
Is it important that the `message` be customizable?

**Comment by jedmao** [comment]
Whoops! Can't actually return the `val`, because that would go against the return type of `asserts val is NonNullable<T>`. Hmm...

**Comment by moltar** [comment]
> Is it important that the message be customizable?

Yes, I think so. Because otherwise it'd be difficult to know where the throw happened.

**Comment by moltar** [comment]
I usually put something like:

```
ensure(widgets.find(...), 'Cannot find widget.')
```

**Comment by jedmao** [comment]
Thanks for the context. Let me mull this over.

**Comment by moltar** [comment]
Awesome! I am liking the error message too with value in it.
